version: '3.1'

services:
  s_api_getway:
    container_name: c_api_getway
    image: hyalitekin/apigeyway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - 80:80
    networks:
      - micro_net
      - int_net


  s_contact_api:
    container_name: c_contact_api
    image: hyalitekin/contactapi
    build: 
      context: .
      dockerfile: Services/ContactAPI/Contact.API/Dockerfile
    ports:
      - 9000:9000
    networks:
      - int_net

    
  s_reservation_api:
    container_name: c_reservation_api
    image: hyalitekin/reservationapi
    build: 
      context: .
      dockerfile: Services/ReservationAPI/Reservation.API/Dockerfile
    ports:
      - 9001:9001
    networks:
      - int_net


networks:
  int_net: #ContactApi ve ReservationApi'nin dış dünyaya açık olmasına gerek yok bundan sebet internel network oluşturuldu.
    driver: overlay
    internal: true
  micro_net: #Dış dünyaya açık olan ApiGetWay'in network'ü
    driver: bridge